#!/usr/bin/env node
/**
 * proof.mjs — runs the site's own QA suite and emits proof/scorecard.json.
 * The scorecard rendered on the page is generated by this script; if the
 * suite fails, no scorecard is written. No fake green.
 */
import { execSync, spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const started = Date.now();

console.log('▸ running playwright suite (smoke + a11y, desktop + mobile)…');
const run = spawnSync('npx', ['playwright', 'test'], { stdio: 'inherit' });
if (run.status !== 0) {
  console.error('✗ suite failed — scorecard NOT written. Fix the failures first.');
  process.exit(run.status ?? 1);
}

const results = JSON.parse(readFileSync('test-results/results.json', 'utf8'));

const gates = {};
function walk(suite, file) {
  for (const child of suite.suites ?? []) walk(child, file ?? child.file ?? suite.file);
  for (const spec of suite.specs ?? []) {
    for (const t of spec.tests ?? []) {
      const project = t.projectName ?? 'default';
      const kind = (spec.file ?? file ?? '').includes('a11y') ? 'a11y' : 'smoke';
      const key = `${kind}-${project}`;
      gates[key] ??= { passed: 0, failed: 0, skipped: 0 };
      const skipped = t.results?.every((r) => r.status === 'skipped');
      const ok = t.results?.every((r) => r.status === 'passed' || r.status === 'skipped');
      if (skipped) gates[key].skipped += 1;
      else if (ok) gates[key].passed += 1;
      else gates[key].failed += 1;
    }
  }
}
walk(results, null);

let commit = 'uncommitted';
try {
  commit = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
} catch { /* first run before initial commit */ }

const totalPassed = Object.values(gates).reduce((a, g) => a + g.passed, 0);
const totalFailed = Object.values(gates).reduce((a, g) => a + g.failed, 0);
const totalSkipped = Object.values(gates).reduce((a, g) => a + g.skipped, 0);

const scorecard = {
  site: 'jt-portfolio',
  generatedAt: new Date().toISOString(),
  commit,
  durationMs: Date.now() - started,
  command: 'npm run proof',
  gates: Object.fromEntries(
    Object.entries(gates).map(([k, g]) => [k, { ...g, green: g.failed === 0 }])
  ),
  totals: { passed: totalPassed, failed: totalFailed, skipped: totalSkipped, green: totalFailed === 0 }
};

mkdirSync('proof', { recursive: true });
writeFileSync('proof/scorecard.json', JSON.stringify(scorecard, null, 2) + '\n');
console.log(`✓ proof/scorecard.json written — ${totalPassed} passed / ${totalFailed} failed / ${totalSkipped} honest-skipped @ ${commit}`);
process.exit(totalFailed === 0 ? 0 : 1);
